export const TestimonialsData = [
  {
    id: 1,
    quote: "Judi Guard sangat membantu membersihkan kolom komentar...",
    author: "Budi Gaming",
    title: "YouTuber Gaming",
    avatarUrl: "https://i.pravatar.cc/100?u=budi",
    rating: 5,
  },
  {
    id: 2,
    quote: "Sebagai pengelola komunitas online, fitur deteksi cepat...",
    author: "Citra Lestari",
    title: "Admin Komunitas Online",
    avatarUrl: "https://i.pravatar.cc/100?u=citra",
    rating: 5,
  },
  {
    id: 3,
    quote: "Awalnya ragu, tapi setelah mencoba, Judi Guard terbukti efektif...",
    author: "Anton W.",
    title: "Content Creator",
    avatarUrl: "https://i.pravatar.cc/100?u=anton",
    rating: 4,
  },
  {
    id: 4,
    quote: "Fitur analitiknya memberikan wawasan mendalam tentang...",
    author: "Dewi Analis",
    title: "Data Scientist",
    avatarUrl: "https://i.pravatar.cc/100?u=dewi",
    rating: 5,
  },
  {
    id: 5,
    quote: "Layanan pelanggan Judi Guard sangat responsif dan membantu...",
    author: "Eka Saputra",
    title: "Digital Marketer",
    avatarUrl: "https://i.pravatar.cc/100?u=eka",
    rating: 4,
  },
  {
    id: 6,
    quote: "Integrasi dengan platform kami berjalan mulus tanpa kendala.",
    author: "Fajar Dev",
    title: "Backend Developer",
    avatarUrl: "https://i.pravatar.cc/100?u=fajar",
    rating: 5,
  },
];
